
camera:
  index: 2
  
  # Разрешение камеры (опционально)
  resolution:
    width: 1280
    height: 720

# Параметры сохранения изображений
image:
  output_dir: "data"
  filename: "user_image.jpg"

# Параметры базы данных
database:
  host: "localhost"
  port: 5433
  name: "face-recognition"
  user: "postgres"
  password: "fID3P8zg"

# Параметры распознавания
similarity: 0.15  # Порог схожести (чем меньше, тем строже сравнение)

# Параметры работы системы
detection_interval: 2  # Интервал в секундах между попытками распознавания
door_open_time: 5      # Время в секундах, на которое открывается дверь после успешного распознавания

# Настройки логирования
logging:
  level: "INFO"  # Уровень логирования: DEBUG, INFO, WARNING, ERROR
